### ISSUE TITLE
About the Use of Pseudo Labels in 3D Detection

### ISSUE THREAD

**Issue by ljwwwiop** [BraveGroup/PointSAM-for-MixSup#2]
Hi there, excellent work on the paper. I've noticed that the experiments seem to primarily utilize a semi-supervised (self-training) paradigm. I'm curious about the specific application of PointSAM for detection/segmentation, so I'm wondering if you could release a detection method code based on opendet/MMDetection? Looking forward to your reply, thank you!

**Comment by YuxueYang1204** [comment]
@ljwwwiop I'm glad to see that our work has caught your attention and appreciation. I'd like to kindly clarify a point that MixSup is a paradigm that utilizes mixed-grained labels for supervision, rather than being primarily focused on semi-supervised methods. The intention behind presenting Table 7 in our paper is to illustrate how our MixSup can collaborate effectively with semi-supervised methods, emphasizing its adaptability and potential for integration.

Additionally, we will release our openpcdet-based detection code no later than July.

**Comment by ljwwwiop** [comment]
Thank you very much for your response. I have also done some work on weakly supervised 3D detection using SAM, and some of it was inspired by your work, so thank you.
